BINARY_NAME := "2026-game"

default:
	@just --list

build:
	go build -o tmp/{{BINARY_NAME}} ./cmd/api
	chmod +x tmp/{{BINARY_NAME}}

run: build
	./tmp/{{BINARY_NAME}}

dev:
	swag init -g cmd/api/main.go -o ./docs && air --build.cmd "go build -o tmp/{{BINARY_NAME}} ./cmd/api" --build.bin "./tmp/{{BINARY_NAME}}"

test:
	go test ./...

lint:
	go fmt ./...
	go vet ./...
	golangci-lint run

generate-docs:
	swag init -g cmd/api/main.go -o ./docs

import-activities-csv csv_path:
	go run ./scripts/generate_activities_import_json -in {{csv_path}} -out data/activities.json
	go run ./cmd/import activities data

import-checks-csv csv_path:
	go run ./scripts/generate_checks_import_json -in {{csv_path}} -out data/activities.json
	go run ./cmd/import activities data

import-users-csv csv_path="data/SITCON_2026_users.csv":
	go run ./scripts/generate_users_from_csv -in {{csv_path}} -out data/user.json
	go run ./cmd/import users data
