name: CI

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - ".github/workflows/docs-ci.yaml"
  pull_request:
    paths:
      - "docs/**"
      - ".github/workflows/docs-ci.yaml"

jobs:
  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      # move to docs directory to read package.json
      - name: Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: docs/pnpm-lock.yaml
      - name: Install dependencies
        working-directory: docs
        run: pnpm install --frozen-lockfile

      - name: Check formatting
        working-directory: docs
        run: pnpm format:check
      
      - name: Check
        working-directory: docs
        run: pnpm test
      
      - name: Build
        working-directory: docs
        run: pnpm build